services:

  nginx:
    image: nginx:latest
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:8080"
    depends_on:
      - client
      # - server

  client:
    container_name: client
    image: client
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    env_file:
      - ./client/.env
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./client/
          target: /app/
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    depends_on:
      - server

  server:
    container_name: server
    image: server
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    env_file:
      - ./server/.env
    ports:
      - "3001:3001"
    develop:
      watch:
        - action: sync
          path: ./server/
          target: /app/
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    depends_on:
      - mysql

  mysql:
    image: "mysql:latest"
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=compu_dev
    volumes:
      - ./mysql:/var/lib/mysql

      #despues de levantar el servicio docker-compose correr 
      # - docker-compose exec server npx prisma migrate dev
      # - docker-compose exec server npx prisma db seed -- --environment (development / production)